name: e_commerce_app
description: A new Flutter application.



publish_to: 'none'











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  google_fonts: ^1.1.1
  flutter_speed_dial: ^1.2.5
  http: ^0.12.2



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:




  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
